move_base:
  
  DWAPlannerROS:
    
    # Goal Tolerance Parametes
    xy_goal_tolerance: 0.1 # original 0,05
    yaw_goal_tolerance: 3.13 # original 0,17
    latch_xy_goal_tolerance: false

    # The distance from the center point of the robot to place an additional scoring point, in meters
    forward_point_distance: 0.105 # original 0,325 .... 0,105 is good
  

  global_costmap:
    
    update_frequency: 5.0
    publish_frequency: 5.0
 
    use_dijkstra: false
    use_quadratic: true
   
    inflation_layer: {inflation_radius: 0.2 , cost_scaling_factor: 50.0}
    # original 1,0 inf rad, 3,0 cost sc fak

    


  local_costmap:
    
    update_frequency: 5.0 # original 10
    publish_frequency: 5.0 # original 10
  
    width: 4
    height: 5

    # With low resolution (>= 0.05), in narrow passways, the obstacle region may 
    # overlap and thus the local planner will not be able to find a path through.
  
    resolution: 0.02
    #resolution: 0.05 #Original

    inflation_layer: {inflation_radius: 0.2 , cost_scaling_factor: 50.0}
    # original 1,0 inf rad, 3,0 cost sc fak

  base_global_planner: navfn/NavfnROS

#  <!-- RVIZ -->
#    <group if="$(arg open_rviz)"> 
#      <node pkg="rviz" type="rviz" name="rviz" required="true"
#          args="-d $(find turtlebot3_navigation)/rviz/turtlebot3_navigation.rviz"/>
#    </group>

#  <arg name="open_rviz" default="true"/>



