move_base:
  
  local_costmap:
    
    update_frequency: 5.0 # original 10
    publish_frequency: 5.0 # original 10
  
    width: 4
    height: 5

    # With low resolution (>= 0.05), in narrow passways, the obstacle region may 
    # overlap and thus the local planner will not be able to find a path through.
  
    resolution: 0.02
    #resolution: 0.05 #Original

    inflation_layer: {inflation_radius: 0.2 , cost_scaling_factor: 50.0}
    # original 1,0 inf rad, 3,0 cost sc fak

